import { Product } from '@/lib/types/product';

export const MOCK_PRODUCTS: Product[] = [
  {
    sku: 'YAM-NMAX-BL01',
    name: 'OEM Front Brake Pads',
    category: 'Brakes',
    stock: 2,
    minThreshold: 5,
    location: 'Rack A-01 / Shelf 2',
    cost: 280,
    wholesale: 380,
    retail: 450,
    oem: true,
    model: 'Yamaha NMAX 155',
    brand: 'Yamaha Genuine Parts'
  },
  {
    sku: 'RCB-NMAX-BP02',
    name: 'RCB S-Series Ceramic Brake Pads',
    category: 'Brakes',
    stock: 14,
    minThreshold: 6,
    location: 'Rack A-01 / Shelf 3',
    cost: 350,
    wholesale: 480,
    retail: 580,
    oem: false,
    model: 'Yamaha NMAX 155',
    brand: 'Racing Boy'
  },
  {
    sku: 'HON-CLK-CVTB',
    name: 'OEM Drive Belt (Gates Bando)',
    category: 'Drivetrain',
    stock: 4,
    minThreshold: 8,
    location: 'Rack B-04 / Shelf 1',
    cost: 520,
    wholesale: 720,
    retail: 850,
    oem: true,
    model: 'Honda Click 125i/150i',
    brand: 'Honda OEM'
  },
  {
    sku: 'UMA-CLK-CVTR',
    name: 'Uma Racing Kevlar High-Tension Belt',
    category: 'Drivetrain',
    stock: 9,
    minThreshold: 4,
    location: 'Rack B-04 / Shelf 2',
    cost: 750,
    wholesale: 1050,
    retail: 1250,
    oem: false,
    model: 'Honda Click 125i/150i',
    brand: 'Uma Racing'
  },
  {
    sku: 'MOT-3100-10W40',
    name: 'Motul 3100 Gold 4T 10W40 (1L)',
    category: 'Fluids',
    stock: 28,
    minThreshold: 15,
    location: 'Aisle 1 / Shelf 1',
    cost: 260,
    wholesale: 330,
    retail: 390,
    oem: false,
    model: 'Universal',
    brand: 'Motul'
  },
  {
    sku: 'SHL-ADV-AX7',
    name: 'Shell Advance AX7 Synthetic 10W40 (1L)',
    category: 'Fluids',
    stock: 18,
    minThreshold: 12,
    location: 'Aisle 1 / Shelf 2',
    cost: 240,
    wholesale: 300,
    retail: 360,
    oem: false,
    model: 'Universal',
    brand: 'Shell'
  },
  {
    sku: 'NGK-CPR8EA9',
    name: 'NGK Nickel Spark Plug (CPR8EA-9)',
    category: 'Ignition',
    stock: 3,
    minThreshold: 10,
    location: 'Rack C-02 / Shelf 1',
    cost: 110,
    wholesale: 150,
    retail: 190,
    oem: true,
    model: 'Honda Click 125i/150i',
    brand: 'NGK'
  },
  {
    sku: 'DEN-IU24-IR',
    name: 'Denso Iridium Power Spark Plug (IU24)',
    category: 'Ignition',
    stock: 11,
    minThreshold: 5,
    location: 'Rack C-02 / Shelf 2',
    cost: 380,
    wholesale: 520,
    retail: 620,
    oem: false,
    model: 'Yamaha NMAX 155',
    brand: 'Denso'
  },
  {
    sku: 'SUZ-RAI-CLUTCH',
    name: 'Raider 150 Fi OEM Clutch Lining Set',
    category: 'Engine',
    stock: 5,
    minThreshold: 4,
    location: 'Rack D-01 / Shelf 3',
    cost: 680,
    wholesale: 890,
    retail: 1100,
    oem: true,
    model: 'Suzuki Raider 150 Fi',
    brand: 'Suzuki OEM'
  },
  {
    sku: 'KTR-RAI-CL6SP',
    name: 'Kawahara 6-Spring Competition Clutch Plate',
    category: 'Engine',
    stock: 7,
    minThreshold: 3,
    location: 'Rack D-01 / Shelf 4',
    cost: 950,
    wholesale: 1300,
    retail: 1550,
    oem: false,
    model: 'Suzuki Raider 150 Fi',
    brand: 'Kawahara Racing'
  },
  {
    sku: 'MIC-PILOT-ST',
    name: 'Michelin Pilot Street 2 (110/80-14)',
    category: 'Tires',
    stock: 6,
    minThreshold: 4,
    location: 'Tire Rack 2 / Floor',
    cost: 1450,
    wholesale: 1850,
    retail: 2150,
    oem: false,
    model: 'Honda ADV 160',
    brand: 'Michelin'
  },
  {
    sku: 'IRC-SCT-OEM',
    name: 'IRC SCT-005 OEM Rear Tire (130/70-13)',
    category: 'Tires',
    stock: 8,
    minThreshold: 4,
    location: 'Tire Rack 1 / Floor',
    cost: 1200,
    wholesale: 1550,
    retail: 1800,
    oem: true,
    model: 'Yamaha NMAX 155',
    brand: 'IRC Tire'
  },
  {
    sku: 'GEN-UNASSIGNED-BRG',
    name: 'Universal Wheel Ball Bearing (6201-2RS)',
    category: 'Accessories',
    stock: 12,
    minThreshold: 5,
    location: '',
    cost: 45,
    wholesale: 75,
    retail: 110,
    oem: false,
    model: 'Universal',
    brand: 'Generic Bearings'
  }
];
